site_name: Base de Datos.
site_url: https://fjagui.github.io/web-bd/
#repo_url: https://github.com/fjagui/web-bd/
#repo_name: web-bd
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navogation.expand
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.action.edit
plugins:
    - search
    - mermaid2

markdown_extensions:
  - toc:
      permalink: true   
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - attr_list
extra_javascript:
  - https://unpkg.com/mermaid@8.8.4/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css
nav:
  - Inicio: index.md
  - Unidad 1: 
      - Teoría: UD1/index.md
      - Actividades: UD1/practicas.md
      - RA y CE: UD1/ra.md
  - Unidad 2: 
      - Teoría: UD2/index.md
      - Actividades: UD2/practicas.md
      - RA y CE: UD2/ra.md
  - Unidad 3: 
      - Teoría: UD3/index.md
      - Actividades: UD3/practicas.md
      - RA y CE: UD3/ra.md
#   - Unidad 4: 
#       - Teoría: UD4/index.md
#       - Actividades: UD4/practicas.md
#       - RA y CE: UD4/ra.md
#   - Unidad 5: 
#       - Teoría: UD5/index.md
#       - Actividades: UD5/practicas.md
#       - RA y CE: UD5/ra.md
#   - Unidad 6: 
#       - Teoría: UD6/index.md
#       - Actividades: UD6/practicas.md
#       - RA y CE: UD6/ra.md
